#!/usr/bin/env sh

# with ruby trace
/opt/mtasc/mtasc -cp "../src" -cp "../test/src" -version 8 -swf ActionStep.swf -header 800:600:20 -trace org.actionstep.ASDebugger.trace -pack org/actionstep -pack org/actionstep/constants -pack org/actionstep/images org/actionstep/test/ASTestMain -main

# without trace
# /opt/mtasc/mtasc -cp "../src" -cp "../test/src" -version 8 -swf ActionStep.swf -header 800:600:20 -pack org/actionstep -pack org/actionstep/images -pack org/actionstep/constants -pack org/actionstep/images org/actionstep/test/ASTestMain -main

echo 'Build complete.'
