#!/usr/bin/env sh
/usr/local/bin/mtasc -cp "../src" -cp "../test/src" -swf ActionStep.swf -header 800:600:20 -version 8 -trace org.actionstep.ASDebugger.debugPanelTrace -pack org/actionstep -pack org/actionstep/constants -pack org/actionstep/images org/actionstep/test/ASTestMain -main
puts 'Build complete.'
